import pandas as pd
colours = pd.Series(["Red","Green","Blue"])
print(colours)
print("#########################################################")
cars = pd.Series(["BMW","Mercedes","Audi"])
print(cars)
print("#########################################################")
cars_data = pd.DataFrame({"Cars":cars,"Colours":colours})
print(cars_data)
print("#########################################################")
car_sales = pd.read_csv(r"D:\Pycharm Projects\machine_learning_and_data_science\Data\car-sales.csv")
print(car_sales)
print("#########################################################")
car_sales.to_csv(r"exported_car_sales.csv")
exported_data = pd.read_csv(r"exported_car_sales.csv")
print("########################### Exported Data #################################")
print(exported_data)
print("#########################################################")
print(car_sales.dtypes)
print("#########################################################")
print(car_sales.describe())
print("#########################################################")
print(car_sales.info())
print("#########################################################")

